DROP TABLE IF EXISTS ASSIGNMENTS;

CREATE TABLE ASSIGNMENTS
(
    aid LONG AUTO_INCREMENT PRIMARY KEY,
    aname VARCHAR(25) NOT NULL,
    adescription VARCHAR(200) NOT NULL,
    ahandindate VARCHAR(10) NOT NULL
);